/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/

var temp = $('.temperature');
var date = $('.date');
var city = '台北市';
var tomDateA=$('#tomDateA');
var tomDateB=$('#tomDateB');
var tomDateC=$('#tomDateC');
var tomTempA=$('#tomTempA');
var tomTempB=$('#tomTempB');
var tomTempC=$('#tomTempC');
var temView=$("#dropdown li a");

$( document ).ready(function() {
    console.log( "ready!" );
    $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+city+'")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys',function(data){
        var item = data.query.results.channel.item;
        var con = item.condition;
        var forecast= item.forecast;
        var curDate= con.date.substr(5,12);
        tomDateA.text(forecast[1].date);
        tomDateB.text(forecast[2].date);
        tomDateC.text(forecast[3].date);
        tomTempA.text(cTof(forecast[1].low)+"-"+cTof(forecast[1].high) + " ℃");
        tomTempB.text(cTof(forecast[2].low)+"-"+cTof(forecast[2].high) + " ℃");
        tomTempC.text(cTof(forecast[3].low)+"-"+cTof(forecast[3].high) + " ℃");
        skycons_state("today",data.query.results.channel.item.condition.text);
        skycons_state("day1",data.query.results.channel.item.forecast[1].text);
        skycons_state("day2",data.query.results.channel.item.forecast[2].text);
        skycons_state("day3",data.query.results.channel.item.forecast[3].text);

        console.log(forecast);
        date.text(curDate);});
});

$("#dropdown li").on('click',function(e){
  city=$(this).text();  
    $('button').text(city);
        $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+city+'")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys',function(data){
        var item = data.query.results.channel.item;
        var con = item.condition;
        var forecast = item.forecast;
        var curTemp = con.temp;
        var curDate= con.date.substr(5,12);
        temp.text(cTof(curTemp));
        tomTempA.text(cTof(forecast[1].low)+"-"+cTof(forecast[1].high) + " ℃");
        tomTempB.text(cTof(forecast[2].low)+"-"+cTof(forecast[2].high) + " ℃");
        tomTempC.text(cTof(forecast[3].low)+"-"+cTof(forecast[3].high) + " ℃");
        skycons_state("today",data.query.results.channel.item.condition.text);
        skycons_state("day1",data.query.results.channel.item.forecast[1].text);
        skycons_state("day2",data.query.results.channel.item.forecast[2].text);
        skycons_state("day3",data.query.results.channel.item.forecast[3].text);
         });
});

$( "#dropdown li a" ).each(function( index,element) {
  var city=$(element).text();
  $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+city+'")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys',function(data){
    var temp=data.query.results.channel.item.condition.temp;
    $(element).text($(element).text()+cTof(temp)+" ℃").addClass("temp");
    $(element).text($(element).text()+"&nbsp"+cTof(temp));
    // $(element).text($(element).text()+"  "+cTof(temp));
    // $(element).append("<span class="2"></span>");
 

  });
});


var skycons = new Skycons();

var skycons_state = function(date,status){
    if(status.search("Sunny") >= 0){
      skycons.set(date, Skycons.CLEAR_DAY);
    }
    else if(status.search("Partly Cloudy") >= 0){
      skycons.set(date, Skycons.PARTLY_CLOUDY_DAY);
    }

    else if(status.search("Cloudy") >= 0){
      skycons.set(date, Skycons.CLOUDY);
    }

    else if(status.search("Rain") >= 0){
      skycons.set(date, Skycons.RAIN);
    }

    else if(status.search("Shower") >= 0){
      skycons.set(date, Skycons.RAIN);
    }
    else if(status.search("Windy") >= 0){
      skycons.set(date, Skycons.WIND);
    }
    else if(status.search("Snow") >= 0){
      skycons.set(date, Skycons.SNOW);
    }

    else if(status.search("Foggy") >= 0){
      skycons.set(date, Skycons.FOG);
    }

    else if(status.search("Thunderstorms") >= 0){
      skycons.set(date, Skycons.RAIN);
    }
}



  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);


function cTof(tem){
  var tem = (tem-32)*(5/9);
  tem = Math.round(tem);
  return tem;
}


